### ISSUE TITLE
255 is not a valid CharacterSet

### ISSUE THREAD

**Issue by ur10ser** [fnmsd/MySQL_Fake_Server#6]
1、复现环境
mysql  Ver 8.0.26 for macos10.15 on x86_64 (Homebrew)
2、报错信息
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-12' coro=<start_mysql_server.<locals>.cb() done, defined at /usr/local/bin/python3/lib/python3.8/asyncio/coroutines.py:122> exception=ValueError('255 is not a valid CharacterSet')>
ValueError: 255 is not a valid CharacterSet

应该是编码问题，试了下mysql文档里的三种编码都不太行

**Comment by fnmsd** [comment]
所用connector的版本太高了，该问题已经修复了。

**Comment by fnmsd** [comment]
Close
