### ISSUE TITLE
连接后，数据库是空的，无法短时间内有效取证

### ISSUE THREAD

**Issue by zhou-0322** [fnmsd/MySQL_Fake_Server#7]
连接后，是空的没有数据，攻击者很快就会关掉，无法获取攻击者相关有效证据

**Comment by zhou-0322** [comment]
> _没有提供说明。_

**Comment by fnmsd** [comment]
工具的利用场景是MySQL JDBC反序列化和文件读取的利用，预期都是连接上即触发，所以数据库并没有内容。
